
spring:
  application:
    name: spring-cloud-sentinel-nacos
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8888
      datasource:
        - nacos:
            server-addr: localhost:8848
            data-id: ${spring.application.name}-sentinel
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow
#server:
#  port: 8888
